let supportBiz=null,supportSession=null,activeTicket=null;const $$=id=>document.getElementById(id);
const statusLabels={new:'Nuevo',in_review:'En revisión',waiting_customer:'Esperando respuesta',resolved:'Resuelto',closed:'Cerrado'};
function supportToast(msg){const e=$$('toast');if(!e)return alert(msg);e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2800)}
function contextText(){return `Negocio: ${supportBiz?.name||'—'} · Página: ${location.pathname.split('/').pop()} · Navegador: ${navigator.userAgent.split(')')[0]}) · ${new Date().toLocaleString('es-MX')}`}
async function loadTickets(){const root=$$('support-list');const {data,error}=await supabaseClient.from('support_tickets').select('id,category,subject,priority,status,created_at,updated_at').eq('business_id',supportBiz.id).order('created_at',{ascending:false});if(error){root.innerHTML=`<div class="ct-empty">Activa el módulo de soporte ejecutando APLICAR_EN_SUPABASE.sql.<br><small>${error.message}</small></div>`;return}if(!data?.length){root.innerHTML='<div class="ct-empty">Aún no tienes solicitudes. Cuando necesites ayuda, escríbenos desde aquí.</div>';return}root.replaceChildren(...data.map(t=>{const a=document.createElement('article');a.className='support-ticket';const left=document.createElement('div');const h=document.createElement('h4');h.textContent=t.subject;const p=document.createElement('p');p.textContent=`Creado ${new Date(t.created_at).toLocaleString('es-MX')}`;const meta=document.createElement('div');meta.className='support-ticket-meta';[t.category,t.priority].forEach(v=>{const s=document.createElement('span');s.textContent=v;meta.appendChild(s)});left.append(h,p,meta);const st=document.createElement('div');st.className='status';st.textContent=statusLabels[t.status]||t.status;a.append(left,st);a.addEventListener('click',()=>openTicket(t));return a}))}

async function openTicket(ticket){activeTicket=ticket;$$('support-thread-card').classList.remove('hidden');$$('support-thread-title').textContent=ticket.subject;$$('support-thread-status').textContent=statusLabels[ticket.status]||ticket.status;await loadThread();$$('support-thread-card').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadThread(){if(!activeTicket)return;const root=$$('support-thread');const {data,error}=await supabaseClient.from('support_messages').select('id,sender_type,message,created_at').eq('ticket_id',activeTicket.id).order('created_at',{ascending:true});if(error){root.innerHTML='<div class="ct-empty">No se pudo cargar la conversación.</div>';return}const first={sender_type:'business',message:activeTicket.description||'Solicitud creada',created_at:activeTicket.created_at};const rows=[first,...(data||[])];root.replaceChildren(...rows.map(m=>{const d=document.createElement('div');d.className=`support-message ${m.sender_type==='platform'?'platform':''}`;const b=document.createElement('b');b.textContent=m.sender_type==='platform'?'Soporte MyCitaGo':'Tu negocio';const p=document.createElement('p');p.textContent=m.message;const sm=document.createElement('small');sm.textContent=new Date(m.created_at).toLocaleString('es-MX');d.append(b,p,sm);return d}));root.scrollTop=root.scrollHeight}
async function sendReply(){if(!activeTicket)return;const text=$$('support-reply').value.trim();if(!text)return;const {error}=await supabaseClient.from('support_messages').insert({ticket_id:activeTicket.id,business_id:supportBiz.id,sender_id:supportSession.user.id,sender_type:'business',message:text});if(error)return supportToast('No se pudo enviar: '+error.message);$$('support-reply').value='';await loadThread();supportToast('Mensaje enviado')}

async function sendTicket(){const subject=$$('support-subject').value.trim(),description=$$('support-description').value.trim();if(!subject)return supportToast('Escribe el tema de la solicitud');const btn=$$('support-send');btn.disabled=true;btn.textContent='Enviando…';try{const payload={business_id:supportBiz.id,created_by:supportSession.user.id,category:$$('support-category').value,subject,description:description||null,priority:$$('support-priority').value,source_page:location.pathname,browser_info:navigator.userAgent};const {error}=await supabaseClient.from('support_tickets').insert(payload);if(error)throw error;$$('support-subject').value='';$$('support-description').value='';supportToast('Solicitud enviada a soporte MyCitaGo');await loadTickets()}catch(e){supportToast('No se pudo enviar: '+e.message)}finally{btn.disabled=false;btn.textContent='Enviar a soporte'}}
async function initSupport(){supportSession=await requireAuth();if(!supportSession)return;supportBiz=await getMyBusiness(supportSession.user);if(!supportBiz)return;$$('support-context').textContent=contextText();$$('support-send').onclick=sendTicket;$$('support-refresh').onclick=loadTickets;$$('support-reply-send').onclick=sendReply;await loadTickets()}
document.addEventListener('DOMContentLoaded',initSupport);
