let agendaBiz=null,anchorDate=new Date(),agendaItems=[],agendaView=localStorage.getItem('mycitago:agenda:view')||'week',agendaBranches=[],agendaStaff=[],agendaServices=[];
const A=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const monday=(d)=>{const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};
const minFromTime=t=>{const [h,m]=String(t||'08:00').slice(0,5).split(':').map(Number);return h*60+m};
function rangeForView(){if(agendaView==='day')return [anchorDate,anchorDate];if(agendaView==='3day')return [anchorDate,add(anchorDate,2)];if(agendaView==='month'){const s=new Date(anchorDate.getFullYear(),anchorDate.getMonth(),1,12),e=new Date(anchorDate.getFullYear(),anchorDate.getMonth()+1,0,12);return[s,e]}const s=monday(anchorDate);return [s,add(s,6)]}
function visibleDays(){const [s,e]=rangeForView();const out=[];for(let d=new Date(s);d<=e;d=add(d,1))out.push(new Date(d));return out}
function filtered(){const br=A('agenda-branch-filter')?.value,st=A('agenda-staff-filter')?.value,sv=A('agenda-service-filter')?.value;return agendaItems.filter(x=>(!br||x.branch_id===br)&&(!st||x.staff_id===st)&&(!sv||x.service_id===sv))}
function labelRange(){const [s,e]=rangeForView();if(agendaView==='month')return s.toLocaleDateString('es-MX',{month:'long',year:'numeric'});if(dateKey(s)===dateKey(e))return s.toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'});return `${s.toLocaleDateString('es-MX',{day:'numeric',month:'short'})} – ${e.toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})}`}
async function loadMeta(){const [br,st,sv]=await Promise.all([supabaseClient.from('business_branches').select('id,name,is_primary,active').eq('business_id',agendaBiz.id).eq('active',true).order('is_primary',{ascending:false}),supabaseClient.from('staff').select('id,name,branch_id,active').eq('business_id',agendaBiz.id).eq('active',true).order('name'),supabaseClient.from('services').select('id,name,active').eq('business_id',agendaBiz.id).eq('active',true).order('name')]);agendaBranches=br.data||[];agendaStaff=st.data||[];agendaServices=sv.data||[];fill(A('agenda-branch-filter'),agendaBranches,'Todas las sucursales');fill(A('agenda-staff-filter'),agendaStaff,'Todos los profesionales');fill(A('agenda-service-filter'),agendaServices,'Todos los servicios')}
function fill(sel,items,label){if(!sel)return;sel.innerHTML=`<option value="">${label}</option>`+items.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
async function loadAgenda(){const [from,to]=rangeForView().map(dateKey);let q=supabaseClient.from('appointments').select('id,business_id,branch_id,staff_id,service_id,appointment_date,start_time,end_time,status,duration_charged,customers(name),services(name,duration_minutes)').eq('business_id',agendaBiz.id).gte('appointment_date',from).lte('appointment_date',to).order('appointment_date').order('start_time');const {data,error}=await q;if(error){console.error(error);agendaItems=[]}else agendaItems=data||[];renderAgenda()}
function renderAgenda(){const items=filtered();A('agenda-range').textContent=labelRange();A('agenda-count').textContent=items.length;A('agenda-confirmed').textContent=items.filter(x=>x.status==='confirmada').length;const booked=items.filter(x=>x.status!=='cancelada').reduce((s,x)=>s+(Number(x.duration_charged||x.services?.duration_minutes)||60),0);A('agenda-utilization').textContent=`${Math.min(100,Math.round(booked/Math.max(1,visibleDays().length*600)*100))}%`;document.querySelectorAll('[data-agenda-view]').forEach(b=>b.classList.toggle('active',b.dataset.agendaView===agendaView));A('agenda-calendar-shell').classList.toggle('hidden',['month','list'].includes(agendaView));A('agenda-month').classList.toggle('hidden',agendaView!=='month');A('agenda-list-shell').classList.toggle('hidden',agendaView!=='list');if(agendaView==='month')renderMonth(items);else if(agendaView!=='list')renderCalendar(items);renderList(items)}
function renderCalendar(items){const days=visibleDays(),head=A('calendar-head');head.style.setProperty('--agenda-cols',days.length);head.innerHTML='<div></div>';days.forEach(d=>{const x=document.createElement('div');x.innerHTML=`<small>${d.toLocaleDateString('es-MX',{weekday:'short'})}</small><strong>${d.toLocaleDateString('es-MX',{day:'numeric',month:'short'})}</strong>`;head.appendChild(x)});const axis=A('time-axis');axis.innerHTML=Array.from({length:13},(_,i)=>`<span>${pad(8+i)}:00</span>`).join('');const grid=A('calendar-grid');grid.style.setProperty('--agenda-cols',days.length);grid.replaceChildren(...days.map(d=>{const col=document.createElement('div');col.className='calendar-day-col';items.filter(a=>a.appointment_date===dateKey(d)).forEach(a=>{const start=minFromTime(a.start_time),dur=Number(a.duration_charged||a.services?.duration_minutes)||60;const ev=document.createElement('button');ev.type='button';ev.className=`calendar-event ${a.status||''}`;ev.style.top=`${Math.max(0,start-480)}px`;ev.style.height=`${Math.max(32,dur)}px`;ev.innerHTML=`<b>${a.customers?.name||'Cliente'}</b><span>${String(a.start_time).slice(0,5)} · ${a.services?.name||'Servicio'}</span>`;col.appendChild(ev)});return col}))}
function renderMonth(items){const root=A('agenda-month'),start=new Date(anchorDate.getFullYear(),anchorDate.getMonth(),1,12),first=(start.getDay()+6)%7,days=new Date(anchorDate.getFullYear(),anchorDate.getMonth()+1,0).getDate();root.innerHTML='<div class="month-weekdays">'+['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<b>${x}</b>`).join('')+'</div><div class="month-grid">'+Array.from({length:first},()=>'<div class="month-cell muted"></div>').join('')+Array.from({length:days},(_,i)=>{const d=i+1,k=dateKey(new Date(anchorDate.getFullYear(),anchorDate.getMonth(),d,12)),day=items.filter(x=>x.appointment_date===k);return `<div class="month-cell"><strong>${d}</strong>${day.slice(0,3).map(x=>`<span>${String(x.start_time).slice(0,5)} ${x.customers?.name||'Cliente'}</span>`).join('')}${day.length>3?`<small>+${day.length-3} más</small>`:''}</div>`}).join('')+'</div>'}
function renderList(items){A('agenda-list').innerHTML=items.length?items.map(a=>`<div class="agenda-list-row"><time>${new Date(a.appointment_date+'T12:00:00').toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'})} ${String(a.start_time).slice(0,5)}</time><div><b>${a.customers?.name||'Cliente'}</b><small>${a.services?.name||'Servicio'}${a.staff_id?' · '+(agendaStaff.find(s=>s.id===a.staff_id)?.name||'Profesional'):''}</small></div><em>${a.status||'Pendiente'}</em></div>`).join(''):'<div class="agenda-empty">No hay citas para esta vista.</div>'}
function step(delta){if(agendaView==='month')anchorDate=new Date(anchorDate.getFullYear(),anchorDate.getMonth()+delta,1,12);else anchorDate=add(anchorDate,delta*(agendaView==='week'?7:agendaView==='3day'?3:1));loadAgenda()}
async function initAgenda(){const s=await requireAuth();if(!s)return;agendaBiz=await getMyBusiness(s.user);if(!agendaBiz)return;anchorDate=new Date();await loadMeta();document.querySelectorAll('[data-agenda-view]').forEach(b=>b.onclick=()=>{agendaView=b.dataset.agendaView;localStorage.setItem('mycitago:agenda:view',agendaView);loadAgenda()});['agenda-branch-filter','agenda-staff-filter','agenda-service-filter'].forEach(id=>A(id).onchange=renderAgenda);A('agenda-prev').onclick=()=>step(-1);A('agenda-next').onclick=()=>step(1);A('agenda-today').onclick=()=>{anchorDate=new Date();loadAgenda()};window.addEventListener('mycitago:appointment-created',loadAgenda);await loadAgenda()}
document.addEventListener('DOMContentLoaded',initAgenda);
