let reviewBiz,reviewRows=[];
const GOOGLE_REVIEWS_CONFIGURED=window.MYCITAGO_GOOGLE_REVIEWS_ENABLED===true;
const R=id=>document.getElementById(id);
function functionError(error,name){const raw=String(error?.message||error||'');const code=String(error?.name||error?.constructor?.name||'');if(/FunctionsFetchError|Failed to send a request|fetch failed|NetworkError/i.test(code+' '+raw))return `No se pudo contactar la función ${name}.`;return raw||'No se pudo completar la operación con Google.'}
async function syncReviews(){if(!GOOGLE_REVIEWS_CONFIGURED)return msg('Integración de Google no configurada.');const {data,error}=await supabaseClient.functions.invoke('google-reviews-sync',{body:{business_id:reviewBiz.id}});if(error)return msg(functionError(error,'google-reviews-sync'));await loadReviews();return data}
async function replyReview(review_id,comment){if(!GOOGLE_REVIEWS_CONFIGURED)return msg('Integración de Google no configurada.');const {error}=await supabaseClient.functions.invoke('google-review-reply',{body:{business_id:reviewBiz.id,review_id,comment}});if(error)return msg(functionError(error,'google-review-reply'));await loadReviews()}
async function connectGoogle(){if(!GOOGLE_REVIEWS_CONFIGURED)return msg('Integración de Google no configurada.');const {data,error}=await supabaseClient.functions.invoke('google-oauth-start',{body:{business_id:reviewBiz.id}});if(error)return msg(functionError(error,'google-oauth-start'));if(data?.authorization_url)location.href=data.authorization_url}
function msg(m){const t=R('toast');if(!t)return;t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
function sourceLabel(x){return x.source==='google'?'Google':'MyCitaGo'}
function normalizeInternal(x){return {...x,star_rating:x.rating,reply_comment:x.reply_text,review_id:x.id,source:x.source||'internal',create_time:x.external_created_at||x.created_at}}
function renderReviews(){const f=R('review-filter')?.value||'';let list=reviewRows;if(f==='unanswered')list=list.filter(x=>!x.reply_comment);else if(f==='low')list=list.filter(x=>Number(x.star_rating)<=3);else if(f)list=list.filter(x=>String(x.star_rating)===f);const host=R('reviews-list');host.replaceChildren();if(!list.length){host.innerHTML='<div class="ct-empty reviews-empty"><strong>Aún no hay reseñas</strong><span>Las reseñas internas aparecerán aquí aunque Google no esté conectado.</span></div>';return}list.forEach(x=>{const a=document.createElement('article');a.className='review-card';a.innerHTML=`<div class="review-head"><div><strong>${String(x.reviewer_name||'Cliente').replace(/[<>]/g,'')}</strong><span class="source-label">${sourceLabel(x)}</span></div><span class="review-stars">${'★'.repeat(Number(x.star_rating||0))}${'☆'.repeat(Math.max(0,5-Number(x.star_rating||0)))}</span></div>${x.comment?`<p>${String(x.comment).replace(/[<>]/g,'')}</p>`:''}${x.reply_comment?`<div class="review-reply">Tu respuesta: ${String(x.reply_comment).replace(/[<>]/g,'')}</div>`:''}<div class="review-actions"><button class="ct-btn ct-btn-secondary" type="button">${x.reply_comment?'Editar respuesta':'Responder'}</button></div>`;a.querySelector('button').onclick=()=>reply(x);host.appendChild(a)})}
async function reply(x){const text=prompt('Respuesta pública:',x.reply_comment||'');if(text===null)return;if(x.source==='google'){if(!GOOGLE_REVIEWS_CONFIGURED)return msg('Integración de Google no configurada.');const {error}=await supabaseClient.functions.invoke('google-review-reply',{body:{business_id:reviewBiz.id,review_id:x.review_id,comment:text.trim()}});if(error)return msg('No se pudo responder en Google.')}else{const {error}=await supabaseClient.rpc('reply_internal_review',{p_review_id:x.review_id,p_reply:text.trim()||null});if(error)return msg('No se pudo guardar la respuesta.')}await loadReviews();msg('Respuesta guardada')}
async function loadReviews(){const {data,error}=await supabaseClient.from('reviews').select('id,source,rating,comment,reviewer_name,reply_text,external_review_id,external_created_at,created_at').eq('business_id',reviewBiz.id).eq('status','published').order('created_at',{ascending:false});if(error){console.error(error);reviewRows=[]}else reviewRows=(data||[]).map(normalizeInternal);const total=reviewRows.length;R('review-total').textContent=total;R('review-rating').textContent=total?(reviewRows.reduce((a,x)=>a+Number(x.star_rating||0),0)/total).toFixed(1)+' ★':'–';renderReviews()}
function setupGoogle(){const connect=R('google-connect'),sync=R('google-sync'),save=R('google-location-save');if(!GOOGLE_REVIEWS_CONFIGURED){[connect,sync,save].forEach(x=>{if(x)x.disabled=true});R('google-status').textContent='Integración no configurada';R('google-status-help').textContent='Las reseñas internas siguen funcionando sin Google.';R('google-config-alert')?.classList.remove('hidden');if(R('google-config-message'))R('google-config-message').textContent='Google Business Profile se habilitará cuando el entorno tenga aprobación y funciones desplegadas.';return}if(connect)connect.onclick=connectGoogle;if(sync)sync.onclick=syncReviews}
async function init(){const s=await requireAuth();if(!s)return;reviewBiz=await getMyBusiness(s.user);if(!reviewBiz)return;R('review-filter').onchange=renderReviews;setupGoogle();await loadReviews()}
document.addEventListener('DOMContentLoaded',init);
