let reviewBiz,reviewRows=[];
const R=id=>document.getElementById(id);
function msg(m,type='info'){const t=R('toast');if(t){t.textContent=m;t.dataset.type=type;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3200)}}
function functionError(error,name){
  const raw=String(error?.message||error||'');
  const code=String(error?.name||error?.constructor?.name||'');
  const unavailable=/FunctionsFetchError|Failed to send a request|fetch failed|NetworkError/i.test(`${code} ${raw}`);
  if(unavailable)return `No se pudo contactar la función ${name}. Debe estar desplegada en Supabase antes de conectar Google.`;
  if(/non-2xx|FunctionsHttpError/i.test(`${code} ${raw}`))return `Google respondió con un error de configuración. Revisa los secretos OAuth de Supabase.`;
  return raw||'No se pudo completar la operación con Google.';
}
function showConfigAlert(message){const box=R('google-config-alert');if(!box)return;R('google-config-message').textContent=message;box.classList.remove('hidden')}
function hideConfigAlert(){R('google-config-alert')?.classList.add('hidden')}
function setConnectionUI(conn){
  const connected=conn?.status==='connected';
  R('google-status').textContent=connected?'Conectado':'No conectado';
  R('google-status-help').textContent=connected?(conn?.display_name||'Perfil autorizado'):'Conecta Google para comenzar';
  const pill=R('google-connection-pill');pill.classList.toggle('connected',connected);pill.classList.toggle('disconnected',!connected);pill.innerHTML=`<i></i> ${connected?'Conectado':'No conectado'}`;
  R('google-connect').querySelector('strong').textContent=connected?'Reconectar Google':'Conectar con Google';
  const name=R('google-connection-name');if(connected&&conn?.display_name){name.textContent=`✓ ${conn.display_name}`;name.classList.remove('hidden')}else name.classList.add('hidden');
  R('google-location-card').classList.toggle('hidden',!connected);
  R('google-sync').disabled=!connected;
}
async function invoke(name,body){const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error)throw new Error(functionError(error,name));if(data?.error)throw new Error(data.error);return data}
async function connectGoogle(){
  const btn=R('google-connect');btn.disabled=true;const old=btn.querySelector('strong').textContent;btn.querySelector('strong').textContent='Abriendo Google…';hideConfigAlert();
  try{const data=await invoke('google-oauth-start',{business_id:reviewBiz.id});if(!data?.authorization_url)throw new Error('Google no devolvió una URL de autorización.');location.href=data.authorization_url}
  catch(e){showConfigAlert(e.message);msg(e.message,'error');btn.disabled=false;btn.querySelector('strong').textContent=old}
}
async function loadGoogleLocations(){const sel=R('google-location');if(!sel)return;const data=await invoke('google-business-locations',{business_id:reviewBiz.id});const locations=data?.locations||[];sel.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=locations.length?'Selecciona una ubicación':'No se encontraron ubicaciones';sel.appendChild(first);locations.forEach((l,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=l.displayName||l.locationName||`Ubicación ${i+1}`;o.dataset.payload=JSON.stringify(l);sel.appendChild(o)});return locations}
async function saveGoogleLocation(){const sel=R('google-location'),opt=sel?.selectedOptions?.[0];if(!opt?.dataset?.payload)throw new Error('Selecciona una ubicación');const selected_location=JSON.parse(opt.dataset.payload);await invoke('google-business-locations',{business_id:reviewBiz.id,selected_location});msg('Ubicación guardada','success');R('google-status-help').textContent=selected_location.displayName||'Google Business Profile';await syncReviews()}
async function syncReviews(){const btn=R('google-sync');btn.disabled=true;const old=btn.textContent;btn.textContent='Actualizando…';try{const data=await invoke('google-reviews-sync',{business_id:reviewBiz.id});reviewRows=data?.reviews||[];R('review-total').textContent=data?.total??reviewRows.length;R('review-rating').textContent=data?.averageRating?`${Number(data.averageRating).toFixed(1)} ★`:'–';renderReviews();msg('Reseñas actualizadas','success')}catch(e){showConfigAlert(e.message);msg(e.message,'error')}finally{btn.disabled=false;btn.textContent=old}}
async function replyReview(review_id,comment){await invoke('google-review-reply',{business_id:reviewBiz.id,review_id,comment});await syncReviews()}
async function deleteReply(review_id){await invoke('google-review-delete-reply',{business_id:reviewBiz.id,review_id});await syncReviews()}
function card(x){const a=document.createElement('article');a.className='review-card';const head=document.createElement('div');head.className='review-head';const name=document.createElement('strong');name.textContent=x.reviewer_name||'Cliente';const stars=document.createElement('span');stars.className='review-stars';stars.textContent='★'.repeat(Number(x.star_rating||0))+'☆'.repeat(Math.max(0,5-Number(x.star_rating||0)));head.append(name,stars);a.appendChild(head);if(x.comment){const p=document.createElement('p');p.textContent=x.comment;a.appendChild(p)}if(x.reply_comment){const d=document.createElement('div');d.className='review-reply';d.textContent='Tu respuesta: '+x.reply_comment;a.appendChild(d)}const actions=document.createElement('div');actions.className='review-actions';const reply=document.createElement('button');reply.className='ct-btn ct-btn-secondary';reply.textContent=x.reply_comment?'Editar respuesta':'Responder';reply.onclick=async()=>{const c=prompt('Respuesta pública en Google:',x.reply_comment||'');if(c?.trim())try{await replyReview(x.review_id,c.trim());msg('Respuesta enviada','success')}catch(e){msg(e.message,'error')}};actions.appendChild(reply);if(x.reply_comment){const del=document.createElement('button');del.className='ct-btn ct-btn-danger';del.textContent='Eliminar respuesta';del.onclick=()=>deleteReply(x.review_id).catch(e=>msg(e.message,'error'));actions.appendChild(del)}a.appendChild(actions);return a}
function renderReviews(){const f=R('review-filter')?.value||'';let list=reviewRows;if(f==='unanswered')list=list.filter(x=>!x.reply_comment);else if(f==='low')list=list.filter(x=>Number(x.star_rating)<=3);else if(f)list=list.filter(x=>String(x.star_rating)===f);const host=R('reviews-list');host.replaceChildren();if(!list.length){const e=document.createElement('div');e.className='ct-empty reviews-empty';e.innerHTML='<strong>Aún no hay reseñas para mostrar</strong><span>Cuando conectes Google y sincronices, aparecerán aquí.</span>';host.appendChild(e);return}list.forEach(x=>host.appendChild(card(x)))}
async function init(){const s=await requireAuth();if(!s)return;reviewBiz=await getMyBusiness(s.user);if(!reviewBiz)return;const {data:conn,error:connError}=await supabaseClient.from('business_google_connections').select('status,display_name,location_id').eq('business_id',reviewBiz.id).maybeSingle();if(connError)console.warn(connError);setConnectionUI(conn);R('google-connect').onclick=connectGoogle;R('google-sync').onclick=syncReviews;R('review-filter').onchange=renderReviews;R('google-location-save').onclick=()=>saveGoogleLocation().catch(e=>{showConfigAlert(e.message);msg(e.message,'error')});if(conn?.status==='connected')loadGoogleLocations().catch(e=>showConfigAlert(e.message));const {data}=await supabaseClient.from('business_google_reviews').select('review_id,reviewer_name,star_rating,comment,create_time,reply_comment').eq('business_id',reviewBiz.id).order('create_time',{ascending:false});reviewRows=data||[];R('review-total').textContent=reviewRows.length;if(reviewRows.length){const avg=reviewRows.reduce((a,x)=>a+Number(x.star_rating||0),0)/reviewRows.length;R('review-rating').textContent=avg.toFixed(1)+' ★'}renderReviews();const params=new URLSearchParams(location.search);if(params.get('google')==='connected'){msg('Google quedó conectado. Selecciona tu ubicación.','success');loadGoogleLocations().catch(e=>showConfigAlert(e.message))}}
window.loadGoogleLocations=loadGoogleLocations;window.saveGoogleLocation=saveGoogleLocation;window.connectGoogle=connectGoogle;window.syncReviews=syncReviews;window.replyReview=replyReview;document.addEventListener('DOMContentLoaded',init);
