import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
export const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
export function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json"}})}
export function adminClient(){return createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!)}
export async function context(req:Request){const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("unauthorized");const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!;const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await userClient.auth.getUser();if(!user)throw new Error("unauthorized");const body=req.method==="GET"?{}:await req.json().catch(()=>({}));const business_id=body.business_id||new URL(req.url).searchParams.get("business_id");if(!business_id)throw new Error("business_id required");const {data:member}=await userClient.from("business_members").select("role,active").eq("business_id",business_id).eq("user_id",user.id).maybeSingle();if(!member||member.active===false)throw new Error("forbidden");return {user,member,business_id,body,admin:adminClient()}}
const enc=new TextEncoder();
function b64url(bytes:Uint8Array){let s="";bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function unb64url(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
export async function signState(payload:any){const secret=Deno.env.get("GOOGLE_STATE_SECRET");if(!secret)throw new Error("GOOGLE_STATE_SECRET missing");const body=b64url(enc.encode(JSON.stringify(payload)));const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(body)));return `${body}.${b64url(sig)}`}
export async function verifyState(state:string){const secret=Deno.env.get("GOOGLE_STATE_SECRET");if(!secret)throw new Error("GOOGLE_STATE_SECRET missing");const [body,sig]=state.split(".");if(!body||!sig)throw new Error("invalid state");const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["verify"]);const ok=await crypto.subtle.verify("HMAC",key,unb64url(sig),enc.encode(body));if(!ok)throw new Error("invalid state signature");const payload=JSON.parse(new TextDecoder().decode(unb64url(body)));if(!payload.business_id||!payload.user_id||Date.now()>payload.exp)throw new Error("expired state");return payload}
export async function getAccessToken(admin:any,business_id:string){const {data:t,error}=await admin.from("business_google_tokens").select("access_token,refresh_token,expires_at").eq("business_id",business_id).maybeSingle();if(error||!t)throw new Error("Google no conectado");const exp=t.expires_at?new Date(t.expires_at).getTime():0;if(t.access_token&&exp>Date.now()+60_000)return t.access_token;if(!t.refresh_token)throw new Error("La autorización de Google expiró. Reconecta Google.");const params=new URLSearchParams({client_id:Deno.env.get("GOOGLE_CLIENT_ID")!,client_secret:Deno.env.get("GOOGLE_CLIENT_SECRET")!,refresh_token:t.refresh_token,grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:params});const j=await r.json();if(!r.ok)throw new Error("No se pudo renovar autorización Google");const expires_at=new Date(Date.now()+Number(j.expires_in||3600)*1000).toISOString();await admin.from("business_google_tokens").update({access_token:j.access_token,expires_at,updated_at:new Date().toISOString()}).eq("business_id",business_id);return j.access_token}
