
const fs=require('fs'),p=require('path'),r=process.argv[2];
const H=fs.existsSync(p.join(r,'reservar.html'))?fs.readFileSync(p.join(r,'reservar.html'),'utf8'):'';
const A=fs.existsSync(p.join(r,'js','app.js'))?fs.readFileSync(p.join(r,'js','app.js'),'utf8'):'';
const S=fs.existsSync(p.join(r,'js','services.js'))?fs.readFileSync(p.join(r,'js','services.js'),'utf8'):'';
const C=fs.existsSync(p.join(r,'css','booking-public-fix.css'))?fs.readFileSync(p.join(r,'css','booking-public-fix.css'),'utf8'):'';
const R=fs.existsSync(p.join(r,'js','public-reviews-verified.js'))?fs.readFileSync(p.join(r,'js','public-reviews-verified.js'),'utf8'):'';
let bad=false; const ok=(c,m)=>{if(!c){console.error('FAIL:',m);bad=true}};
ok(H.includes('booking-desktop-grid'),'falta layout 3 columnas');
ok(H.includes('desktop-reviews-rail'),'falta rail reseñas');
ok(H.includes('desktop-gallery-rail'),'falta rail galería');
ok(H.includes('btn-recommend-business'),'falta recomendar');
ok(H.includes('hero-rating'),'falta rating portada');
ok(R.includes('public_business_reviews_verified'),'helper no usa reseñas verificadas');
ok(A.includes('updateReviewSurfaces'),'no sincroniza hero/rail/mobile');
ok(A.includes('navigator.share'),'recomendar no usa share');
ok(A.includes('navigator.clipboard'),'falta fallback copiar');
ok(S.includes('service.image_url || serviceFallbackImage'),'servicio sin imagen real/fallback');
ok(C.includes('grid-template-columns:minmax(220px,260px) minmax(0,1fr) minmax(220px,260px)'),'grid desktop incorrecto');
ok(C.includes('@media(max-width:980px)'),'falta responsive');
ok(C.includes('.desktop-gallery-rail[hidden]'),'galería no se oculta si no hay datos');
ok(R.includes('fetchVerifiedPublicReviews'),'helper reseñas no existe');
process.exit(bad?1:0);
