import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const shell=read('js/citago-shell.js');
assert.match(shell,/MyCitaGo/);
assert.match(shell,/ayuda\.html/);
const dash=read('css/admin-dashboard-pro.css');
assert.match(dash,/--mycitago-dashboard-compact/);
assert.match(dash,/hero-new-appointment/);
const svc=read('js/admin-services.js');
for(const token of ['SERVICE_TEMPLATE_LIBRARY','calculateServiceIntelligence','applyServiceTemplate','schedule_mode','internal_cost']) assert.ok(svc.includes(token),token);
assert.ok(fs.existsSync('admin/ayuda.html'));
assert.ok(fs.existsSync('js/admin-support.js'));
assert.ok(fs.existsSync('sql/product_upgrade_schema.sql'));
const platform=read('admin/plataforma.html');
for(const token of ['Soporte','Plantillas','Centro de operaciones']) assert.ok(platform.includes(token),token);
const sql=read('sql/product_upgrade_schema.sql');
for(const token of ['service_templates','support_tickets','support_messages','service_commercial_settings','service_versions']) assert.ok(sql.includes(token),token);
assert.ok(fs.existsSync('assets/brand/mycitago-logo.png'));
assert.ok(fs.existsSync('assets/service-presets/barber-cut.svg'));
console.log('full MyCitaGo upgrade contract OK');
