import assert from 'node:assert/strict';
import fs from 'node:fs';
const sql=fs.readFileSync('sql/phase7_reputation_growth_superadmin.sql','utf8');
for(const name of ['business_invites','business_category_change_requests','create_review_request','get_review_request_public','submit_internal_review','track_booking_source']) assert.ok(sql.includes(name),`missing ${name}`);
assert.ok(sql.includes('is_platform_admin()'),'must reuse platform admin function');
assert.ok(!sql.includes('service_role key'),'must not expose service role');
const reviewHtml=fs.readFileSync('resena.html','utf8');
assert.ok(reviewHtml.includes('review-choice-google'),'public review must support Google choice');
assert.ok(reviewHtml.includes('review-choice-internal'),'public review must support MyCitaGo choice');
const reviews=fs.readFileSync('js/admin-reviews.js','utf8');
assert.ok(reviews.includes("from('reviews')"),'admin reviews must read unified reviews');
assert.ok(reviews.includes('source-label'),'admin reviews must label source');
const booking=fs.readFileSync('js/appointments.js','utf8');
assert.ok(booking.includes('bookingSource'),'booking flow must carry source');
assert.ok(booking.includes("rpc('track_booking_source'"),'booking must persist source securely');
const shell=fs.readFileSync('js/citago-shell.js','utf8');
assert.ok(shell.includes("['crecimiento','Crecimiento','crecimiento.html'"),'shell must expose Growth');
assert.ok(fs.existsSync('admin/crecimiento.html'),'growth page missing');
console.log('phase7 reputation/growth contract OK');
