import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
assert.ok(fs.existsSync('js/ui-theme.js'),'missing UI theme controller');
const theme=read('js/ui-theme.js');
assert.match(theme,/data-theme.*light|setAttribute\(['"]data-theme['"],['"]light['"]\)/s);
assert.ok(!theme.includes("prefers-color-scheme: dark"),'dark mode must not auto-enable');
const shell=read('js/citago-shell.js');
assert.ok(!shell.includes('data-theme-toggle'),'admin shell must not expose theme switch');
const login=read('admin/login.html');
assert.ok(!login.includes('login-theme-toggle'),'login must not expose theme switch');
assert.match(login,/btn-google/);
assert.match(login,/signInWithOAuth/);
assert.match(login,/provider:\s*['"]google['"]/);
assert.match(login,/country-code/);
assert.match(login,/\+52/);
const landing=read('index.html');
assert.ok(!landing.includes('id="theme-toggle"'),'landing must not expose theme switch');
assert.ok(fs.existsSync('supabase/functions/complete-onboarding/index.ts'),'missing oauth onboarding edge function');
console.log('light UI + Google auth contract OK');
